# Generated by Django 2.2.1 on 2019-08-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtext', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'conntestdb',
            },
        ),
    ]
