# Generated by Django 2.2.1 on 2019-08-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_dbcontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='url',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='keywords',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
