# Generated by Django 2.2.1 on 2019-08-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190829_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dic',
            old_name='index',
            new_name='local_index',
        ),
    ]
